spring:
  application:
    name: RAIL-API-GATEWAY
  cloud:
    gateway:
      routes:
      - id: RAIL-SERVICE
        uri:
         http://localhost:7071
        predicates:
        - Path=/rail-service/**

      - id: RAIL-EMPLOYEE
        uri:
          http://localhost:7072
        predicates:
        - Path=/rail-employee/**

eureka:
 client:
   fetch-registry: true
   register-with-eureka: true
   service-url:
    defaultZone : http://localhost:7070/eureka
 instance:
   prefer-ip-address: true

server:
  port: 7073